### PR TITLE
Update writing-tests.md - Shown test code is wrong

### PR DESCRIPTION
**Pull request by sparkylein**
Change `errorf` to `Errorf` in shown test code..

### CODE REVIEW

**Comment by sparkylein** [comment]
Playing a bit with the code reveals that in order to pass the test GetPi needs to return `3.14159265358979323846264338327950288419716939937510582097494459`.

However, `outln` cannot print out the full number, only `3.14159`.
Is this by design?

Thanks

**Review by mertcandav — APPROVED** [review]
LGTM!

**Comment by mertcandav** [comment]
> Playing a bit with the code reveals that in order to pass the test GetPi needs to return `3.14159265358979323846264338327950288419716939937510582097494459`.
> 
> However, `outln` cannot print out the full number, only `3.14159`. Is this by design?

In many languages, will not be printed with full-precision and precision varies implementation to implementation.
In Jule, the built-in `outln` function uses API's conversion algorithms. Naturally, `std::conv` is not implemented for API, therefore the C++ API uses conversion algorithm of C++ STL by default. And STL converts as `3.14159`. But if you are using `std::fmt` to print values, it will use `std::conv` package to convert string. The default format call is `conv::FmtFloat(f64(arg), 'g', -1, 64)` for `f64` types, quoted from implementation source code. And it will be converted as `3.141592653589793`.

For example:
```
use math for std::math
use fmt for std::fmt

fn main() {
    outln(math::Pi)
    fmt::Println(math::Pi)
}
```

If you need more precision or any custom format, call the relevant function of `std::conv` package.

For example:
```
use math for std::math
use conv for std::conv

fn main() {
    outln(conv::FmtFloat(math::Pi, 'f', 5, 64))
    outln(conv::FmtFloat(math::Pi, 'g', -1, 64))
    outln(conv::FmtFloat(math::Pi, 'f', 48, 64))
    outln(conv::FmtFloat(math::Pi, 'e', 48, 64))
    outln(conv::FmtFloat(math::Pi, 'f', 20, 64))
    outln(conv::FmtFloat(math::Pi, 'f', 8, 64))
}
```

> BTW: Just realized that there is not only the `errorf` in the code, but there is a second one in the text; which I overlooked. Sorry.

No problem. I'll update relevant outdated codes.


Thanks for your contribution.

**Comment by sparkylein** [comment]
Thank you for the thorough explanation about the print functions.
Maybe it's a good idea to copy and paste what you explained here into the manual, as I'm sure I'm not the only one to find this explanation excellent.

**Pull request merged**
